{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "07f6b0dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas\n",
    "import keras\n",
    "import tensorflow as tf\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.utils import shuffle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "b0c24204",
   "metadata": {},
   "outputs": [],
   "source": [
    "seed = 7\n",
    "np.random.seed(seed)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "569fe29b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(60,)"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# read dataset using pandas as dataframe\n",
    "dataframe = pandas.read_csv(\"/Users/hraj18/Desktop/sonar.csv\", header=None)\n",
    "dataset = dataframe.values\n",
    "\n",
    "X = dataset[:, 0:60].astype(float)\n",
    "y = dataset[:, 60]\n",
    "\n",
    "X[0].shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "db4d46f6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# baseline model\n",
    "def baseline_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dense(60, activation='relu', input_shape=(60,)))\n",
    "    model.add(Dense(60, activation='relu'))\n",
    "    model.add(Dense(1, activation='sigmoid'))\n",
    "    model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "a30a94a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# smaller model\n",
    "def smaller_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dense(60, activation='relu', input_shape=(60,)))\n",
    "    model.add(Dense(30, activation='relu'))\n",
    "    model.add(Dense(1, activation='sigmoid'))\n",
    "    model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "a9ae710f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# bigger model\n",
    "def bigger_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dense(60, activation='relu', input_shape=(60,)))\n",
    "    model.add(Dense(60, activation='relu'))\n",
    "    model.add(Dense(30, activation='relu'))\n",
    "    model.add(Dense(1, activation='sigmoid'))\n",
    "    model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "0dc2df7b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# functional model\n",
    "def functional_model():\n",
    "    inputs = keras.Input(shape=(60,))\n",
    "    layer1 = Dense(60, activation='relu')(inputs)\n",
    "    layer2 = Dense(60, activation='relu')(layer1)\n",
    "    outputs = Dense(1, activation='sigmoid')(layer2)\n",
    "\n",
    "    model = keras.Model(inputs, outputs)\n",
    "    model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6cfe162a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# model subclassing\n",
    "class MyModel(tf.keras.Model):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.dense1 = Dense(60, activation = 'relu')\n",
    "        self.dense2 = Dense(60, activation = 'relu')\n",
    "        self.dense3 = Dense(1, activation = 'sigmoid')\n",
    "\n",
    "    def call(self, inputs):\n",
    "        x = self.dense1(inputs)\n",
    "        x = self.dense2(x)\n",
    "        return self.dense3(x)\n",
    "    \n",
    "def subclass_model():\n",
    "    inputs = keras.Input(shape=(60,))\n",
    "    mymodel = MyModel()\n",
    "    outputs = mymodel.call(inputs)\n",
    "\n",
    "    model = keras.Model(inputs, outputs)\n",
    "    model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "    \n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "143818c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# encode labels\n",
    "le = LabelEncoder()\n",
    "encoded_y = le.fit(y).transform(y)\n",
    "# encoded_y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "96d3ca80",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2427852680.py:2: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
      "  estimator = KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)\n",
      "2022-10-18 22:33:05.440882: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Basline: Accuracy 84.11%, Error (4.28%)\n"
     ]
    }
   ],
   "source": [
    "# evaluating baseline model\n",
    "estimator = KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)\n",
    "kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(estimator, X, encoded_y, cv=kfold)\n",
    "print(\"Basline: Accuracy %.2f%%, Error (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8c7695ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2230371169.py:5: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
      "  estimators.append(('mlp', KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Standardized: Accuracy 86.50%, Error (4.81%)\n"
     ]
    }
   ],
   "source": [
    "# evaluating baseline model with standardized dataset\n",
    "np.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasClassifier(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, encoded_y, cv=kfold)\n",
    "print(\"Standardized: Accuracy %.2f%%, Error (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "cacf5ad8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# custom K-Fold without sci-kit & shuffle the data\n",
    "dataframe = shuffle(dataframe)\n",
    "\n",
    "dataset = dataframe.values\n",
    "\n",
    "X = dataset[:, 0:60].astype(float)\n",
    "y = dataset[:, 60]\n",
    "\n",
    "# label encoding\n",
    "le = LabelEncoder()\n",
    "encoded_y = le.fit(y).transform(y)\n",
    "\n",
    "k=10\n",
    "num_val_samples = len(X)//k\n",
    "num_epochs = 100\n",
    "\n",
    "all_acc = np.array([])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "fe1cfeeb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing K-Fold # 1\n",
      "Processing K-Fold # 2\n",
      "Processing K-Fold # 3\n",
      "Processing K-Fold # 4\n",
      "Processing K-Fold # 5\n",
      "Processing K-Fold # 6\n",
      "Processing K-Fold # 7\n",
      "Processing K-Fold # 8\n",
      "Processing K-Fold # 9\n",
      "Processing K-Fold # 10\n",
      "+--------------------+\n",
      "Custom K-Folds: Accuracy 86.00%, Error (5.83%)\n"
     ]
    }
   ],
   "source": [
    "# processing k-folds\n",
    "for i in range(k):\n",
    "    print('Processing K-Fold #', i+1)\n",
    "    val_data = X[i * num_val_samples: (i + 1) * num_val_samples]\n",
    "    val_targets = encoded_y[i * num_val_samples: (i + 1) * num_val_samples]\n",
    "\n",
    "    partial_train_data = np.concatenate(\n",
    "        [X[:i * num_val_samples],\n",
    "         X[(i + 1) * num_val_samples:]],\n",
    "        axis=0)\n",
    "    \n",
    "    partial_train_targets = np.concatenate(\n",
    "        [encoded_y[:i * num_val_samples],\n",
    "         encoded_y[(i + 1) * num_val_samples:]],\n",
    "        axis=0)\n",
    "    \n",
    "    model = functional_model()\n",
    "    history = model.fit(partial_train_data, partial_train_targets,\n",
    "        epochs=num_epochs, batch_size=5, verbose=0, validation_data=(val_data, val_targets))\n",
    "    \n",
    "    results = model.evaluate(val_data, val_targets, verbose=0)\n",
    "    \n",
    "#     all_err = np.append(all_err, results[0])\n",
    "    all_acc = np.append(all_acc, results[1])\n",
    "    \n",
    "print(\"+--------------------+\")    \n",
    "print(\"Custom K-Folds: Accuracy %.2f%%, Error (%.2f%%)\" % (all_acc.mean()*100, all_acc.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "6cdeb0ac",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/3417026467.py:5: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
      "  estimators.append(('mlp', KerasClassifier(build_fn=smaller_model, epochs=100, batch_size=5, verbose=0)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Smaller: Accuracy 86.02%, Error (4.10%)\n"
     ]
    }
   ],
   "source": [
    "# evaluating smaller model with standardized dataset\n",
    "np.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasClassifier(build_fn=smaller_model, epochs=100, batch_size=5, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, encoded_y, cv=kfold)\n",
    "print(\"Smaller: Accuracy %.2f%%, Error (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "a386f3a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/4000243666.py:5: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
      "  estimators.append(('mlp', KerasClassifier(build_fn=functional_model, epochs=100, batch_size=5, verbose=0)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Functional Api: Accuracy 84.12%, Error (4.35%)\n"
     ]
    }
   ],
   "source": [
    "# evaluating functional_api model with standardized dataset\n",
    "np.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasClassifier(build_fn=functional_model, epochs=100, batch_size=5, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, encoded_y, cv=kfold)\n",
    "print(\"Functional Api: Accuracy %.2f%%, Error (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "9d38910f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model Subclassing: Accuracy nan%, Error (nan%)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/1324557355.py:5: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
      "  estimators.append(('mlp', KerasClassifier(build_fn=subclass_model, epochs=100, batch_size=5, verbose=0)))\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 349, in __setattr__\n",
      "    self._base_model_initialized\n",
      "AttributeError: 'MyModel' object has no attribute '_base_model_initialized'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 248, in fit\n",
      "    return super().fit(x, y, **kwargs)\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 164, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 16, in subclass_model\n",
      "    mymodel = MyModel()\n",
      "  File \"/var/folders/kh/4ngydqvn2lqc3s0_m4zsp1c00000gn/T/ipykernel_16547/2725597705.py\", line 5, in __init__\n",
      "    self.dense1 = Dense(60, activation = 'relu')\n",
      "  File \"/Users/hraj18/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 351, in __setattr__\n",
      "    raise RuntimeError(\n",
      "RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "# evaluating subclassing model with standardized dataset\n",
    "np.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasClassifier(build_fn=subclass_model, epochs=100, batch_size=5, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, encoded_y, cv=kfold)\n",
    "print(\"Model Subclassing: Accuracy %.2f%%, Error (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "516168da",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
